name: Nightly tests

on:
  # Run every two days at 0:01 UTC
  schedule:
    - cron: '1 0 */2 * *'
  # Allow manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-upstream:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.9", "3.13"]

    name: Test (${{ matrix.os }}) - py ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: true

    - name: Install dependencies (Linux)
      if: startsWith( matrix.os, 'ubuntu' )
      run: |
        echo "setuptools!=78.0.1" >> ruciospark_constraints.txt
        export UV_BUILD_CONSTRAINT="$(pwd)/ruciospark_constraints.txt"
        export GIT_LFS_SKIP_SMUDGE=1
        uv pip install --upgrade pip setuptools wheel pytest-xdist
        # Install upstream packages from their main branches
        uv pip install git+https://github.com/scikit-hep/awkward.git
        uv pip install git+https://github.com/scikit-hep/uproot5.git
        uv pip install git+https://github.com/dask-contrib/dask-awkward.git
        uv pip install git+https://github.com/scikit-hep/vector.git
        uv pip install git+https://github.com/dask-contrib/dask-histogram.git
        # mltool installs
        # c.f. https://github.com/astral-sh/uv/issues/3437
        uv pip install torch --index-url https://download.pytorch.org/whl/cpu
        uv pip install xgboost
        # install checked out coffea
        uv pip install -q '.[dev,parsl,dask,spark]' --upgrade
        uv pip list

    - name: Install dependencies (MacOS)
      if: matrix.os == 'macOS-latest'
      run: |
        echo "setuptools!=78.0.1" >> ruciospark_constraints.txt
        export UV_BUILD_CONSTRAINT="$(pwd)/ruciospark_constraints.txt"
        export GIT_LFS_SKIP_SMUDGE=1
        uv pip install --upgrade pip setuptools wheel pytest-xdist
        # Install upstream packages from their main branches
        uv pip install git+https://github.com/scikit-hep/awkward.git
        uv pip install git+https://github.com/scikit-hep/uproot5.git
        uv pip install git+https://github.com/dask-contrib/dask-awkward.git
        uv pip install git+https://github.com/scikit-hep/vector.git
        uv pip install git+https://github.com/dask-contrib/dask-histogram.git
        # mltool installs
        # c.f. https://github.com/astral-sh/uv/issues/3437
        uv pip install torch
        uv pip install xgboost
        # install checked out coffea
        uv pip install -q '.[dev,dask]' --upgrade
        uv pip list

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $env:GIT_LFS_SKIP_SMUDGE = "1"
        uv pip install --upgrade pip setuptools wheel pytest-xdist
        # Install upstream packages from their main branches
        uv pip install git+https://github.com/scikit-hep/awkward.git
        uv pip install git+https://github.com/scikit-hep/uproot5.git
        uv pip install git+https://github.com/dask-contrib/dask-awkward.git
        uv pip install git+https://github.com/scikit-hep/vector.git
        uv pip install git+https://github.com/dask-contrib/dask-histogram.git
        # mltool installs
        # c.f. https://github.com/astral-sh/uv/issues/3437
        uv pip install torch
        uv pip install xgboost
        # install checked out coffea
        uv pip install -q '.[dev,dask]' --upgrade
        uv pip list

    - name: Test with pytest (without dask Client - run in parallel)
      run: |
        python -m pytest --cov-report=xml --cov=coffea --deselect=test_taskvine -m "not dask_client" -n 4

    - name: Test with pytest (with dask Client)
      run: |
        python -m pytest --cov-report=xml --cov=coffea --deselect=test_taskvine -m "dask_client"
